
version: 2
updates:

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "development"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "codeinwp/themeisle-sdk"
