version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - 8055:80
    privileged: true
    volumes:
      - core:/var/www/html
      - .:/var/www/html/wp-content/themes/neve/
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_ROOT_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1

  cli:
    image: wordpress:cli
    restart: always
    privileged: true
    volumes:
      - core:/var/www/html
      - .:/var/www/html/wp-content/themes/neve/
    depends_on:
      - mysql
      - wordpress
volumes:
  core:
