name: Bug report
description: Report a bug so we can get to squashing it.
labels: bug
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      attributes:
          label: Description
          description: Please write a brief description of the bug, including what you expect to happen and what is currently happening.
          placeholder: |
              Feature '...' is not working properly. I expect '...' to happen, but '...' happens instead
      validations:
          required: true

    - type: textarea
      attributes:
          label: Step-by-step reproduction instructions
          description: Please write the steps needed to reproduce the bug.
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording, code snippet
          description: |
              If possible, please upload a screenshot or screen recording which demonstrates the bug.
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. 
      validations:
          required: false

    - type: input
      attributes:
          label: Environment info
          description: |
              Please share a https://pastebin.com/ link of your system details by going to site Admin -> Tools -> Site Health -> Info and Copy to Clipboard
          placeholder: pastebin.com/ ... 
      validations:
          required: false

    - type: dropdown
      id: regression
      attributes:
          label: Is the issue you are reporting a regression 
          description: |
            i.e, a previously working feature/functionality is now broken? 
            By specifying whether or not your issue is a regression, it will help the development team to more effectively diagnose and resolve the problem.
          
          multiple: false
          options:
              - 'No'
              - 'Yes, this is a regression.'
      validations:
          required: true
 
