name: Feature request
description: Suggest a feature that we can implement.
labels: new feature
body:
- type: textarea
  attributes:
    label: What problem does this address?
    description: | 
      Can you give us a little more insight into this feature request? We'd love to know if it's related to any problems or pain points you've been facing. 
      If so, can you please let us know what the issue is in a clear and simple way? 
      Tip: If this is related to a customer request, please add the Help Scout thread URL.
    placeholder: | 
     For example, something like "I find it tough when..." or "I get frustrated because..." would be great. 
  validations:
    required: true
- type: textarea
  attributes:
    label: What is your proposed solution?
    description: Can you please specify the desired feature or improvement and how it resolves the problem mentioned?
  validations:
    required: false
- type: dropdown
  id: doc-needed
  attributes:
      label: Will this feature require documentation? (Optional)
      description: |
        Does this feature require the creation or update of documentation? If you're unsure, feel free to skip this.
      multiple: false
      options:
          - 'I dont know.'
          - 'No.'
          - 'Yes, it requires documentation.'
  validations:
      required: false