export const BuildersData = {
	header: {
		id: 'hfg_header_layout',
		control_id: 'hfg_header_layout',
		panel: 'hfg_header',
		section: 'hfg_header_layout_section',
		title: 'Header',
		devices: {
			desktop: 'Desktop',
			mobile: 'Mobile',
		},
		items: {
			button_base: {
				name: 'Button',
				description: null,
				id: 'button_base',
				width: 2,
				section: 'header_button',
				icon: 'admin-links',
				previewImage: null,
				componentSlug: 'hfg-button',
				elementOrder: 0,
			},
			custom_html: {
				name: 'HTML',
				description: null,
				id: 'custom_html',
				width: 3,
				section: 'custom_html',
				icon: 'welcome-write-blog',
				previewImage: null,
				componentSlug: 'hfg-html',
				elementOrder: 1,
			},
			logo: {
				name: 'Logo & Site Identity',
				description:
					'Display your company logo here or simply use words to describe your business.',
				id: 'logo',
				width: 3,
				section: 'title_tagline',
				icon: 'admin-appearance',
				previewImage:
					'http://localhost:8081/wp-content/themes/neve-git/header-footer-grid/assets/images/customizer/component-site-logo.jpg',
				componentSlug: 'hfg-logo',
				elementOrder: 2,
			},
			'nav-icon': {
				name: 'Menu Icon',
				description: null,
				id: 'nav-icon',
				width: 1,
				section: 'header_menu_icon',
				icon: 'menu',
				previewImage: null,
				componentSlug: 'nav-icon',
				elementOrder: 3,
			},
			'primary-menu': {
				name: 'Primary Menu',
				description: null,
				id: 'primary-menu',
				width: 6,
				section: 'header_menu_primary',
				icon: 'tagcloud',
				previewImage: null,
				componentSlug: 'hfg-primary-menu',
				elementOrder: 4,
			},
			header_search: {
				name: 'Search Form',
				description: null,
				id: 'header_search',
				width: 2,
				section: 'header_search',
				icon: 'code-standards',
				previewImage: null,
				componentSlug: 'hfg-search-form',
				elementOrder: 5,
			},
			header_search_responsive: {
				name: 'Search Icon',
				description: null,
				id: 'header_search_responsive',
				width: 1,
				section: 'header_search_responsive',
				icon: 'search',
				previewImage: null,
				componentSlug: 'hfg-generic-component',
				elementOrder: 6,
			},
			'secondary-menu': {
				name: 'Secondary Menu',
				description: null,
				id: 'secondary-menu',
				width: 6,
				section: 'secondary_menu_primary',
				icon: 'tagcloud',
				previewImage: null,
				componentSlug: 'hfg-generic-component',
				elementOrder: 7,
			},
		},
		rows: {
			top: {
				title: 'Header Top',
				description:
					'Design your Header by dragging, dropping and resizing all the elements in real-time. <br/><a target="_blank" href="https://docs.themeisle.com/article/946-neve-doc#header">Read full documentation</a>.',
			},
			main: {
				title: 'Header Main',
				description:
					'Design your Header by dragging, dropping and resizing all the elements in real-time. <br/><a target="_blank" href="https://docs.themeisle.com/article/946-neve-doc#header">Read full documentation</a>.',
			},
			bottom: {
				title: 'Header Bottom',
				description:
					'Design your Header by dragging, dropping and resizing all the elements in real-time. <br/><a target="_blank" href="https://docs.themeisle.com/article/946-neve-doc#header">Read full documentation</a>.',
			},
			sidebar: {
				title: 'Mobile menu content',
				description:
					'Design your Header by dragging, dropping and resizing all the elements in real-time. <br/><a target="_blank" href="https://docs.themeisle.com/article/946-neve-doc#header">Read full documentation</a>.',
			},
		},
	},
	footer: {
		id: 'hfg_footer_layout',
		control_id: 'hfg_footer_layout',
		panel: 'hfg_footer',
		section: 'hfg_footer_layout_section',
		title: 'Footer',
		devices: {
			desktop: 'Footer',
		},
		items: {
			footer_copyright: {
				name: 'Copyright',
				description: null,
				id: 'footer_copyright',
				width: 2,
				section: 'footer_copyright',
				icon: 'nametag',
				previewImage: null,
				componentSlug: 'hfg-generic-component',
				elementOrder: 0,
			},
			'footer-four-widgets': {
				name: 'Footer Four',
				description: null,
				id: 'footer-four-widgets',
				width: 3,
				section: 'sidebar-widgets-footer-four-widgets',
				icon: 'welcome-widgets-menus',
				previewImage: null,
				componentSlug: 'hfg-generic-component',
				elementOrder: 1,
			},
			'footer-menu': {
				name: 'Footer Menu',
				description: null,
				id: 'footer-menu',
				width: 6,
				section: 'footer_menu_primary',
				icon: 'tagcloud',
				previewImage: null,
				componentSlug: 'hfg-generic-component',
				elementOrder: 2,
			},
			'footer-one-widgets': {
				name: 'Footer One',
				description: null,
				id: 'footer-one-widgets',
				width: 3,
				section: 'sidebar-widgets-footer-one-widgets',
				icon: 'welcome-widgets-menus',
				previewImage: null,
				componentSlug: 'hfg-generic-component',
				elementOrder: 3,
			},
			'footer-three-widgets': {
				name: 'Footer Three',
				description: null,
				id: 'footer-three-widgets',
				width: 3,
				section: 'sidebar-widgets-footer-three-widgets',
				icon: 'welcome-widgets-menus',
				previewImage: null,
				componentSlug: 'hfg-generic-component',
				elementOrder: 4,
			},
			'footer-two-widgets': {
				name: 'Footer Two',
				description: null,
				id: 'footer-two-widgets',
				width: 3,
				section: 'sidebar-widgets-footer-two-widgets',
				icon: 'welcome-widgets-menus',
				previewImage: null,
				componentSlug: 'hfg-generic-component',
				elementOrder: 5,
			},
		},
		rows: {
			top: {
				title: 'Footer Top',
				description:
					'Design your Footer by dragging, dropping and resizing all the elements in real-time. <br/><a target="_blank" href="https://docs.themeisle.com/article/946-neve-doc#footer-builder">Read full documentation</a>.',
			},
			bottom: {
				title: 'Footer Bottom',
				description:
					'Design your Footer by dragging, dropping and resizing all the elements in real-time. <br/><a target="_blank" href="https://docs.themeisle.com/article/946-neve-doc#footer-builder">Read full documentation</a>.',
			},
		},
	},
};
