name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@master 
      with:
        repo-token: "${{ secrets.BOT_TOKEN }}"
        enable-versioned-regex: 0
        configuration-path: .github/labeler.yml