name: Sync 30 branch
on:
  push:
    branches:
      - 'development'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge development -> new/3-0
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: development
          target_branch: new/3-0
          github_token: ${{ secrets.BOT_TOKEN }}
