name: Mirror branch

on:
  push:
    branches: [ development ]

jobs:
  mirror-to-new30:
    runs-on: ubuntu-latest
    steps:
      - uses: zofrex/mirror-branch@v1
        with:
          target-branch: new/3-0
          force: false
