name: VerifyIssue

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
    branches:
      - development
  check_run:

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    name: Ensure Pull Request has a linked issue.
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}