name: Update Google Fonts
on:
  schedule:
    - cron: '0 0 * * 1' #  00:00 every monday
jobs:
  update-fonts:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
          extensions: simplexml
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ci/update-fonts
          token: ${{ secrets.BOT_TOKEN }}
      - name: Merge development -> ci/update-fonts
        uses: Codeinwp/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: ci/update-fonts
          github_token: ${{ secrets.BOT_TOKEN }}
      - name: Update Fonts
        run: php ./bin/update-google-fonts.php ${{ secrets.GOOGLE_TOKEN }}
        env:
          GOOGLE_TOKEN: ${{secrets.GOOGLE_TOKEN}}
      - name: Commit & Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: Update Google fonts"
          token: ${{ secrets.BOT_TOKEN }}
          title: "Update Google Fonts"
          author: themeisle[bot] <${{ secrets.BOT_EMAIL }}>
          branch: ci/update-fonts
          base: development
          body: |
            ### Checklist Before Merge:
            - [ ] There are no removed fonts;
            - [ ] Only `globals/google-fonts.php` has been changed;
