name: Update Google Fonts
on:
  push:
    branches:
      - act/update-g-fonts
jobs:
  update-fonts:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
          extensions: simplexml
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ci/update-fonts
      - name: Merge development -> ci/update-fonts
        uses: Codeinwp/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: ci/update-fonts
          github_token: ${{ secrets.BOT_TOKEN }}
      - name: Update Fonts
        run: php ./bin/update-google-fonts.php ${{ secrets.GOOGLE_TOKEN }}
        env:
          GOOGLE_TOKEN: ${{secrets.GOOGLE_TOKEN}}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Setup Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest
      - name: Run PHPCBF
        run: composer run format-fix-exit
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update google fonts'
          file_pattern: 'globals/google-fonts.php'
          commit_author: themeisle[bot] <${{ secrets.BOT_EMAIL }}>
          commit_user_name: themeisle[bot]
          commit_user_email: ${{ secrets.BOT_EMAIL }}
